[package]
name = "api"
version = "0.1.0"
authors = ["Eden Reich <eden.reich@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
rocket_contrib = "0.4.2"
serde = "1.0.60"
serde_derive = "1.0.103"
serde_json = "1.0"